config/routes.rb
Rails.application.routes.draw do
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  # get 'confirm_registration', to: 'registrations#confirm'
  resource :registration, only: [:new, :create]
  resources :passwords, param: :token
  resources :objectives, only: [:create, :update, :destroy]


  get 'sign_in', to: 'sessions#new', as: :new_session
  post 'sign_in', to: 'sessions#create', as: :create_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_session
  
  get 'account', to: 'users#account', as: :account
  resources :users do
    member do
      patch :update_profile_image
      delete :delete_profile_image
    end
  end
  
  post 'objective/rate', to: 'objectives#rate', as: :rate_objective
  get 'objective/:id', to: 'objectives#details', as: :objective_details

  get 'leader_dashboard', to: 'leaders#dashboard', as: :leader_dashboard
  
  get 'admin_dashboard', to: 'admins#dashboard', as: :admin_dashboard

  get 'users_roles', to: 'users#show_all', as: :users_roles

  patch 'users_roles.:id', to: 'users#set_user_role', as: :set_user_role

  get 'leadership', to: 'leaderships#show', as: :leadership
  post 'leadership', to: 'leaderships#create', as: :leadership_create
  delete 'leadership.:id', to: 'leaderships#destroy', as: :leadership_destroy


  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
end

app/views/admin/_leadership.html.erb
<div class="bg-tertiary p-4 rounded-lg shadow-md w-[400px] mb-6 h-fit">
  <p class="text-quaternary text-xs mb-2">Leader</p>
  <div class="flex items-center gap-4 mb-4">
    <div class="flex w-12 h-12 rounded-full overflow-hidden border-2 border-secondary">
      <%= image_tag(leader.profile_image || 'default_profile.png', class: 'w-full h-full object-cover') %>
    </div>
    <div>
      <h1 class="text-lg text-secondary font-bold"><%= leader.name.titleize %> <%= leader.surname.titleize %></h1>
      <p class="text-quaternary text-sm"><%= leader.email_address %></p>
    </div>
  </div>
  <p class="text-quaternary text-xs ml-8 mb-2">Employees assigned</p>
  <% leaderships.each do |leadership| %>
    <div class="flex items-center gap-4 mb-2 ml-8 justify-between">
      <div class="flex items-center gap-4">
        <div class="flex w-12 h-12 rounded-full overflow-hidden border-2 border-blue-400">
          <%= image_tag(leadership.employee.profile_image || 'default_profile.png', class: 'w-full h-full object-cover') %>
        </div>
        <div>
          <h1 class="text-base text-blue-400 font-bold"><%= leadership.employee.name.titleize %> <%= leadership.employee.surname.titleize %></h1>
          <p class="text-quaternary text-sm"><%= leadership.employee.email_address %></p>
        </div>
      </div>
      <%= form_with(model: leadership, url: leadership_path(leadership.id), method: :delete, local: true) do |form| %>
        <div class="flex justify-end">
          <%= button_tag type: "submit", class: "text-red-500 cursor-pointer" do %>
            <span class="material-icons">delete</span>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/admin/dashboard.html.erb
<script>
  function redirectToObjective(objectiveId) {
    window.location.href = "objective/" + objectiveId;
  }
</script>
<div class="bg-primary px-4 py-6 text-quaternary min-h-screen">
  <h1 class="text-3xl font-bold mb-6 text-white">Admin Dashboard</h1>
  <p class="mb-4">Your employees' objectives</p>
  <div class="mb-4">
    <%= form_with(url: admin_dashboard_path, method: :get, local: true) do |form| %>
      <div class="flex items-center gap-2">
        <%= form.text_field :query, value: params[:query], placeholder: "Search objectives...", class: "p-2 rounded w-full border border-quaternary bg-tertiary" %>
        <%= form.submit "Search", class: "bg-secondary text-primary px-4 py-2 rounded cursor-pointer hover:opacity-50" %>
      </div>
    <% end %>
  </div>
  <div>
    <table class="border border-quaternary w-full">
      <thead class="bg-tertiary text-secondary">
        <tr>
          <th class="text-left px-6 py-3 border-b font-bold uppercase tracking-wider">Employee</th>
          <th class="text-left px-6 py-3 border-b font-bold uppercase tracking-wider">Title</th>
          <th class="text-left px-6 py-3 border-b font-bold uppercase tracking-wider">Status</th>
          <th class="text-left px-6 py-3 border-b font-bold uppercase tracking-wider">Description</th>
          <th class="text-left px-6 py-3 border-b font-bold uppercase tracking-wider">Estimated date</th>
          <th class="text-left px-6 py-3 border-b font-bold uppercase tracking-wider">Rating</th>
        </tr>
      </thead>
      <tbody class="divide-y divide-gray-200">
        <% @objectives.each do |objective| %>
          <tr class="hover:bg-tertiary hover:text-quaternary transition-colors duration-200 cursor-pointer" 
              data-id="<%= objective.id %>" 
              onClick="redirectToObjective(<%= objective.id %>)">
            <td class="px-6 py-4 whitespace-nowrap">
              <%= objective.employee.name.capitalize %> <%= objective.employee.surname.capitalize %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <%= objective.title %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <div class="rounded-full border px-2 w-fit"
                style="<%= case objective.status
                    when 'New' then 'color: white; border: 1px solid white;'
                    when 'In_Progress' then 'color:#fddf69; border: 1px solid #fddf69;'
                    when 'In_Review' then 'color: #df69fd; border: 1px solid #df69fd;'
                    else 'color:  #69fd95; border: 1px solid #69fd95;'
                  end %> padding-left: 8px; padding-right: 8px;">
                <%= objective.status.titleize %>
              </div>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <%= truncate(objective.description, length: 50) %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <%= objective.estimated_completion_at.strftime('%d/%m/%Y') %>
            </td>
            <td class="px-6 py-4 whitespace-nowrap">
              <%= objective.rating.present? ? "#{objective.rating} / 5" : "Not rated yet" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div id="objectiveModal" class="fixed inset-0 flex items-center justify-center w-screen h-screen text-quaternary bg-primary bg-opacity-80" style="display: none;">
  <div class="bg-primary text-quaternary p-6 rounded shadow-lg max-h-fit w-[700px]" style="width: 700px;">
    <div id="modal-loader" class="absolute inset-0 flex items-center justify-center bg-primary bg-opacity-80" style="display: none;">
      <div class="loader"></div>
    </div>
    <div id="modal-content" style="display: none;">
      <div class="flex justify-between items-center mb-4 w-full">
        <h2 id="modal-title" class="text-xl font-bold text-secondary">Objective Title</h2>
        <button onClick="closeModal()" class="text-red-500 hover:text-gray-800 text-2xl">&times;</button>
      </div>
      <p id="modal-description" class="mb-4">Objective Description</p>
      <p id="modal-status" class="mb-2">Status: </p>
      <p id="modal-estimated-date" class="mb-2">Estimated Completion: </p>
      <p id="modal-rating" class="mb-2">Rating: </p>
      <%= form_with url: rate_objective_path, method: :post, id: "rating-form", local: true do |form| %>
        <input type="hidden" name="id" id="objective-id">
        <div class="flex align-center gap-2">
          <p class="text-secondary font-bold leading-4">Change Rating</p>
          <select name="rating" id="rating" class="py-1 px-2 border border-secondary rounded max-w-fit">
            <option value="">Select</option>
            <% (1..5).each do |rating| %>
              <option value="<%= rating %>"><%= rating %> / 5</option>
            <% end %>
          </select>
          <button type="submit" class="bg-secondary text-primary px-2 py-1 rounded hover:opacity-75">Save</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/leaderships.html.erb
<script>
  const newObjetctiveModal = () => {
    const modal = document.getElementById('newObjectiveModal');
    modal.style.display = 'flex';
  }

  const closeModal = () => {
    const modal = document.getElementById('newObjectiveModal');
    modal.style.display = 'none';
  }
</script>
<div class="bg-primary px-4 py-6 text-quaternary min-h-screen">
  <div class="flex gap-4 items-center align-middle mb-4">
    <h1 class="text-3xl font-bold text-white">Leaderships</h1>
    <button onClick="newObjetctiveModal()" class="flex items-center justify-center rounded-full bg-secondary hover:bg-[#8ed600]">
      <span class="material-icons text-primary">add</span>
    </button>
    <% if @leaderships.empty? %>
      <span class="material-icons text-secondary animate-marquee">arrow_back</span>
    <% end %>
  </div>
  <div class="flex flex-wrap w-full gap-4">
    <% if @leaderships_grouped_by_leader.present? %>
      <% @leaderships_grouped_by_leader.each do |leader, leaderships| %>
        <%= render partial: 'admin/leadership', locals: { leader: leader, leaderships: leaderships } %>
      <% end %>
    <% else %>
      <p class="text-white">No leaderships found</p>
    <% end %>
  </div>
</div>
<div id="newObjectiveModal" class="fixed inset-0 flex items-center justify-center w-screen h-screen text-quaternary bg-primary bg-opacity-80" style="display: none;">
  <div class="bg-primary text-quaternary p-6 rounded shadow-lg max-h-fit w-[700px]" style="width: 700px;">
    <div class="flex justify-between items-center mb-4 w-full">
      <h2 class="text-xl font-bold text-secondary">New Leasership</h2>
      <button onClick="closeModal()" class="text-red-500 hover:text-gray-800 text-2xl">&times;</button>
    </div>
    <%= form_with(model: Leadership.new, url: leadership_create_path, local: true) do |form| %>
      <div class="mb-4">
        <p>Leader Email Address</p>
        <%= form.email_field :leader_email, class: "w-full p-2 rounded bg-tertiary", required: true %>
      </div>
      <div class="mb-4">
        <p>Employee Email Address</p>
        <%= form.email_field :employee_email, class: "w-full p-2 rounded bg-tertiary", required: true %>
      </div>
      <div class="flex justify-end">
        <%= form.submit "Save", class: "bg-blue-500 text-white px-4 py-2 rounded bg-tertiary cursor-pointer hover:bg-opacity-50" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users_roles.html.erb
<div class="bg-primary px-4 py-6 text-quaternary min-h-screen">
  <div class="flex gap-4 items-center align-middle mb-4">
    <h1 class="text-3xl font-bold text-white">Assign Roles</h1>
  </div>
  <div class="flex flex-wrap w-full gap-4">
    <%= render partial: 'user_role_section', locals: { users: @admins, role_name: 'Admins' } %>
    <div class="w-full flex justify-center gap-4">
      <%= render partial: 'user_role_section', locals: { users: @leaders, role_name: 'Leaders' } %>
      <%= render partial: 'user_role_section', locals: { users: @employees, role_name: 'Employees' } %>
    </div>
  </div>
</div>