config/routes.rb
Rails.application.routes.draw do
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  # get 'confirm_registration', to: 'registrations#confirm'
  resource :registration, only: [:new, :create]
  resources :passwords, param: :token
  resources :objectives, only: [:create, :update, :destroy]


  get 'sign_in', to: 'sessions#new', as: :new_session
  post 'sign_in', to: 'sessions#create', as: :create_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_session
  
  get 'account', to: 'users#account', as: :account
  resources :users do
    member do
      patch :update_profile_image
      delete :delete_profile_image
    end
  end
  
  post 'objective/rate', to: 'objectives#rate', as: :rate_objective
  get 'objective/:id', to: 'objectives#details', as: :objective_details

  get 'leader_dashboard', to: 'leaders#dashboard', as: :leader_dashboard
  
  get 'admin_dashboard', to: 'admins#dashboard', as: :admin_dashboard

  get 'users_roles', to: 'users#show_all', as: :users_roles

  patch 'users_roles.:id', to: 'users#set_user_role', as: :set_user_role

  get 'leadership', to: 'leaderships#show', as: :leadership
  post 'leadership', to: 'leaderships#create', as: :leadership_create
  delete 'leadership.:id', to: 'leaderships#destroy', as: :leadership_destroy


  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_secure_token :confirmation_token
  has_many :sessions, dependent: :destroy

  # Associations with inverse_of and dependent options
  has_many :objectives, foreign_key: :employee_id, class_name: "Objective", inverse_of: :employee

  has_many :leaderships, foreign_key: :leader_id, class_name: "Leadership", inverse_of: :leader, dependent: :destroy
  has_many :employees, through: :leaderships, source: :employee, inverse_of: :leaders

  has_many :inverse_leaderships, foreign_key: :employee_id, class_name: "Leadership", inverse_of: :employee, dependent: :destroy
  has_many :leaders, through: :inverse_leaderships, source: :leader, inverse_of: :employees

  normalizes :email_address, with: ->(e) { e.strip.downcase }
  validates :email_address, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validate :validate_profile_image_size

  def confirm!
    update!(confirmed_at: Time.current, confirmation_token: nil)
  end

  def confirmed?
    confirmed_at.present?
  end

  def send_confirmation_instructions
    regenerate_confirmation_token
    UserMailer.confirmation_instructions(self).deliver_now
  end

  def validate_profile_image_size
    return if profile_image.blank?

    # Decode Base64 to calculate the size
    size_in_bytes = Base64.decode64(profile_image).bytesize
    max_size_in_bytes = 1.megabyte

    if size_in_bytes > max_size_in_bytes
      errors.add(:profile_image, "The image is too large. The maximum size is 1MB.")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def account
    @user = current_user
    @leaders = @user.leaders || []
    @employees = @user.employees || []
  end

  def show_all
    @users_group_by_role = User.all.order(:name).group_by(&:role)
    @admins = @users_group_by_role["admin"] || []
    @employees = @users_group_by_role["employee"] || []
    @leaders = @users_group_by_role["leader"] || []
    render "admin/users_roles"
  end

  def set_user_role
    @user = User.find(params[:id])
    if current_user.role == "admin"
      @user.update(role: params[:user][:role])
      redirect_to users_roles_path
    else
      flash[:alert] = "You are not authorized to change roles."
      redirect_to account_path
    end
  end


  def update_profile_image
    @user = current_user

    if params[:user][:profile_image].present?
      file = params[:user][:profile_image]

      size_in_bytes = file.size
      max_size_in_bytes = 1.megabyte

      if size_in_bytes > max_size_in_bytes
        flash[:alert] = "The image is too large. The maximum size is 1MB."
        render :account and return
      end

      base64_image = Base64.strict_encode64(file.read)
      mime_type = file.content_type

      if @user.update(profile_image: "data:#{mime_type};base64,#{base64_image}")
        flash[:notice] = "Profile image updated successfully."
        redirect_to account_path
      else
        flash[:alert] = @user.errors[:profile_image].first
        render :account
      end
    else
      flash[:alert] = "No image selected."
      render :account
    end
  end

  def delete_profile_image
    @user = current_user
    @user.update(profile_image: nil)
    flash[:notice] = "Profile image deleted successfully."
    redirect_to account_path
  end

  private

  def set_user
    @user = User.find(params[:id] || current_user.id)
  end

  def user_params
    if current_user.admin? || @user == current_user
      params.require(:user).permit(:profile_image, :role, :name, :surname)
    else
      params.require(:user).permit(:profile_image, :name, :surname)
    end
  end
end

app/views/users/_user_role_section.html.erb
<div class="bg-tertiary p-4 rounded-lg shadow-md w-full mb-6 h-fit">
  <div class="flex items-center gap-4 mb-4">
    <div>
      <h1 class="text-lg text-secondary font-bold"><%= role_name %></h1>
    </div>
  </div>
  <% users.each do |user| %>
    <div class="flex items-center gap-4 mb-2 ml-8 justify-between">
      <div class="flex items-center gap-4">
        <div class="flex w-12 h-12 rounded-full overflow-hidden border-2 border-blue-400">
          <%= image_tag(user.profile_image || 'default_profile.png', class: 'w-full h-full object-cover') %>
        </div>
        <div>
          <h1 class="text-base text-blue-400 font-bold"><%= user.name.titleize %> <%= user.surname.titleize %></h1>
          <p class="text-quaternary text-sm"><%= user.email_address %></p>
        </div>
      </div>
      <% if user.role != 'admin' %>
        <%= form_with(model: user, url: set_user_role_path(user), method: :patch, local: true) do |form| %>
          <div>
            <%= form.select :role, 
                ['leader', 'employee'].map { |key| [key.titleize, key] },
                { include_blank: false }, 
                class: "rounded-sm bg-tertiary text-quaternary text-sm py-1",
                onchange: 'this.form.submit()' %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/account.html.erb
<script>
  function submitForm() {
    const form = document.getElementById('profile-image-form');
    form.submit();
  }
</script>
<div class="bg-primary shadow-lg min-h-screen px-16 items-center flex flex-col">
  <div class="flex w-[870px] flex-col gap-4  justify-center">
    <!-- Datos del Usuario -->
    <h2 class="text-2xl font-bold mb-6 text-white pt-10">User Settings</h2>
    <div class="flex flex-col items-center mb-6 w-full gap-12">
      <div class="flex items-center justify-between w-full">
        <div class="flex gap-4 items-center">
          <div class="flex w-32 h-32 rounded-full overflow-hidden border-2 border-secondary">
            <%= image_tag(@user.profile_image || 'default_profile.png', alt: 'Imagen de perfil', class: 'w-full h-full object-cover') %>
          </div>
          <div>
            <p class="text-lg text-white mt-2"><strong>Upload your profile image</strong></p>
            <p class="text-quaternary text-sm">The image must not exceed 1MB</p>
          </div>
        </div>
        <div class="flex gap-4 items-center justify-center">
          <%= form_with(model: @user, url: update_profile_image_user_path(@user), local: true, html: { enctype: "multipart/form-data", id: "profile-image-form" }) do |form| %>
            <div>
              <%= form.file_field :profile_image, id: "profile_image", class: "hidden", onchange: "submitForm()" %>
              <label for="profile_image" class="cursor-pointer bg-tertiary hover:bg-[#252e3d] text-white py-2 px-4 rounded">
                Upload image
              </label>
            </div>
          <% end %>
          <%= form_with(model: @user, url: delete_profile_image_user_path(@user), method: :delete, local: true) do %>
            <div class="flex justify-end">
              <%= button_tag type: "submit", class: "bg-red-500 text-white px-3 flex items-center h-[36px] rounded hover:bg-red-600 cursor-pointer" do %>
                <span class="material-icons">delete</span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <hr class="w-full border-tertiary h-[1px]"/>
      <div class="min-w-full p-4 rounded-sm">
        <div class="mb-4 flex gap-2 items-center justify-center">
          <div class="flex-1">
            <label class="block text-quaternary" for="user_name">Name:</label>
            <p class="w-full p-2 bg-tertiary rounded text-white"><%= @user.name.capitalize || '-' %></p>
          </div>
          <div class="flex-1">
            <label class="block text-quaternary" for="user_surname">Surname:</label>
            <p class="w-full p-2 bg-tertiary rounded text-white"><%= @user.surname.capitalize || '-' %></p>
          </div>
        </div>
        <div class="mb-4">
          <label class="block text-quaternary" for="user_email">Email:</label>
          <p class="w-full p-2 bg-tertiary rounded text-white"><%= @user.email_address %></p>
        </div>
        <div class="mb-4">
          <label class="block text-quaternary" for="user_role">Role:</label>
          <p class="w-full p-2 bg-tertiary rounded text-white"><%= @user.role.capitalize %></p>
        </div>
      </div>
      <% if current_user.role == 'leader' %>
        <hr class="w-full  border-tertiary h-[1px]"/>
        <div class="min-w-full p-4 rounded-sm flex flex-col align-middle">
          <h3 class="min-w-full text-2xl font-semibold text-white mb-4 self-start">Assigned Employees</h3>
          <% if @employees.present? && @employees.any? %>
            <ul class="flex gap-4 flex-wrap max-w-[870px] w-fit">
              <% @employees.each do |employee| %>
                <li class="p-3 bg-tertiary rounded-lg shadow-md flex items-center gap-4 w-[400px] text-sm">
                  <div class="flex w-16 h-16 rounded-full overflow-hidden border-2 border-tertiary">
                    <%= image_tag(employee.profile_image || 'default_profile.png', alt: 'Imagen de perfil', class: 'w-full h-full object-cover') %>
                  </div>
                  <div class="flex flex-col gap-1 justify-center">
                    <div class="flex gap-2 items-center">
                      <p class="text-quaternary">Name:</p>
                      <p class="text-white"><%= employee.name.capitalize || "No specified" %></p>
                    </div>
                    <div class="flex gap-2 items-center">
                      <p class="text-quaternary">Email:</p>
                      <p class="text-white truncate"><%= employee.email_address || "No specified" %></p>
                    </div>
                  </div>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p class="text-quaternary">No employees assigned</p>
          <% end %>
        </div>
      <% end %>
      <hr class="w-full  border-tertiary h-[1px]"/>
      <div class="min-w-full p-4 rounded-sm flex flex-col align-middle">
        <h3 class="min-w-full text-2xl font-semibold text-white mb-4 self-start">Assigned Leaders</h3>
        <% if @leaders.present? && @leaders.any? %>
          <ul class="flex gap-4 flex-wrap max-w-[870px] w-fit">
            <% @leaders.each do |leader| %>
              <li class="p-3 bg-tertiary rounded-lg shadow-md flex items-center gap-4 w-[400px] text-sm">
                <div class="flex w-16 h-16 rounded-full overflow-hidden border-2 border-tertiary">
                  <%= image_tag(leader.profile_image || 'default_profile.png', alt: 'Imagen de perfil', class: 'w-full h-full object-cover') %>
                </div>
                <div class="flex flex-col gap-1 justify-center">
                  <div class="flex gap-2 items-center">
                    <p class="text-quaternary">Name:</p>
                    <p class="text-white"><%= leader.name.capitalize || "No specified" %></p>
                  </div>
                  <div class="flex gap-2 items-center">
                    <p class="text-quaternary">Email:</p>
                    <p class="text-white truncate"><%= leader.email_address || "No specified" %></p>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p class="text-quaternary">No leaders assigned</p>
        <% end %>
      </div>
    </div>
  </div>
</div>