config/routes.rb
Rails.application.routes.draw do
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  # get 'confirm_registration', to: 'registrations#confirm'
  resource :registration, only: [:new, :create]
  resources :passwords, param: :token
  resources :objectives, only: [:create, :update, :destroy]


  get 'sign_in', to: 'sessions#new', as: :new_session
  post 'sign_in', to: 'sessions#create', as: :create_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_session
  
  get 'account', to: 'users#account', as: :account
  resources :users do
    member do
      patch :update_profile_image
      delete :delete_profile_image
    end
  end
  
  post 'objective/rate', to: 'objectives#rate', as: :rate_objective
  get 'objective/:id', to: 'objectives#details', as: :objective_details

  get 'leader_dashboard', to: 'leaders#dashboard', as: :leader_dashboard
  
  get 'admin_dashboard', to: 'admins#dashboard', as: :admin_dashboard

  get 'users_roles', to: 'users#show_all', as: :users_roles

  patch 'users_roles.:id', to: 'users#set_user_role', as: :set_user_role

  get 'leadership', to: 'leaderships#show', as: :leadership
  post 'leadership', to: 'leaderships#create', as: :leadership_create
  delete 'leadership.:id', to: 'leaderships#destroy', as: :leadership_destroy


  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @objective = Objective.new
    if current_user.role == "admin"
      @objectives = Objective.includes(:employee, :rater).all
      render "admin/dashboard"
    else
      @objectives = Objective.where(employee: current_user).includes(:employee, :rater).order(status: :asc, created_at: :asc)
      render "home/employee_dashboard"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_objective.html.erb
<div class="bg-tertiary p-4 rounded shadow">
  <div class="flex justify-between items-center align-middle">
    <div class="flex items-center gap-4">
      <h2 class="font-bold text-xl text-white">
        <%= objective.title.titleize %>
      </h2>
      <div class="rounded-full border px-2 text-xs"
              style="<%= case objective.status
                  when 'New' then 'color: white; border: 1px solid white;'
                  when 'In_Progress' then 'color:#fddf69; border: 1px solid #fddf69;'
                  when 'In_Review' then 'color: #df69fd; border: 1px solid #df69fd;'
                  else 'color:  #69fd95; border: 1px solid #69fd95;'
                end %> padding-left: 8px; padding-right: 8px;">
        <%= objective.status.titleize %>
      </div>
    </div>
    <% if !objective.rating.present? %>
      <div class="flex gap-4 items-center align-middle">
        <%= form_with(model: objective, local: true) do |form| %>
          <div>
            <%= form.select :status, 
                                  Objective.statuses.map { |key, _value| [key.titleize, key] },
                                  { include_blank: false }, 
                                  class: "rounded-sm bg-tertiary text-quaternary text-sm py-1",
                                  onchange: 'this.form.submit()' %>
          </div>
        <% end %>
        <%= form_with(model: objective, url: objective_path(objective), method: :delete, local: true) do |form| %>
          <div class="flex justify-end">
            <%= button_tag type: "submit", class: "text-red-500 cursor-pointer" do %>
              <span class="material-icons">delete</span>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <p class="text-gray-500 p-4"><%= objective.description %></p>
  <div class="flex gap-1">
    <p class="text-sm text-gray-500">
      Estimated date <%= objective.estimated_completion_at.strftime('%d/%m/%Y') %>
    </p>
    <% if (objective.estimated_completion_at - 3.days) < Time.now %>
      <span class="material-icons text-red-500 text-md">priority_high</span>
      <p class="text-red-500 text-sm leading-2"> <%= ((objective.estimated_completion_at - Time.now) / 1.day).to_i %> days left</p>
    <% end %>
    <% if (objective.estimated_completion_at - 7.days) < Time.now && (objective.estimated_completion_at - 3.days) > Time.now %>
      <span class="material-icons text-yellow-400 text-md">priority_high</span>
      <p class="text-yellow-400 text-sm leading-2"> <%= ((objective.estimated_completion_at - Time.now) / 1.day).to_i %> days left</p>
    <% end %>
  </div>
  <% if objective.rating.present? %>
    <div class="flex items-center gap-2">
      <p class="text-sm text-secondary font-semibold">
        <%= objective.rating %> / 5 
      </p>
      <span class="material-icons text-secondary text-sm">star</span>
      <p class="text-quaternary text-sm">Rated by:</p>
      <p class="text-sm text-secondary font-semibold">
        <%= objective.rater.name.capitalize %>
      </p>
    </div>
  <% else %>
    <div class="flex items-center gap-2">
      <span class="material-icons text-quaternary text-sm">star</span>
      <p class="text-quaternary text-sm">Without rating</p>
    </div>
  <% end %>
</div>

app/views/home/employee_dashboard.html.erb
<script>
  const newObjetctiveModal = () => {
    const modal = document.getElementById('newObjectiveModal');
    modal.style.display = 'flex';
  }

  const closeModal = () => {
    const modal = document.getElementById('newObjectiveModal');
    modal.style.display = 'none';
  }
</script>
<div class="px-4 py-6 bg-primary min-h-screen">
  <div class="flex gap-4 items-center align-middle">
    <h1 class="text-3xl font-bold text-white">My Objectives</h1>
    <button onClick="newObjetctiveModal()" class="flex items-center justify-center rounded-full bg-secondary hover:bg-[#8ed600]">
      <span class="material-icons text-primary">add</span>
    </button>
    <% if @objectives.empty? %>
      <span class="material-icons text-secondary animate-marquee">arrow_back</span>
    <% end %>
  </div>
  <p class="text-gray-600 mb-4">These are your current objectives</p>
  <div class="space-y-4">
    <% if @objectives.empty? %>
      <p class="text-gray-500">You don't have any objectives yet</p>
    <% end %>
    <%= render partial: 'objective', collection: @objectives %>
  </div>
</div>
<div id="newObjectiveModal" class="fixed inset-0 flex items-center justify-center w-screen h-screen text-quaternary bg-primary bg-opacity-80" style="display: none;">
  <div class="bg-primary text-quaternary p-6 rounded shadow-lg max-h-fit w-[700px]" style="width: 700px;">
    <div class="flex justify-between items-center mb-4 w-full">
      <h2 class="text-xl font-bold text-secondary">New Objective</h2>
      <button onClick="closeModal()" class="text-red-500 hover:text-gray-800 text-2xl">&times;</button>
    </div>
    <%= form_with(model: Objective.new, url: objectives_path, local: true) do |form| %>
      <div class="mb-4">
        <p>Title</p>
        <%= form.text_field :title, class: "w-full p-2 rounded bg-tertiary", required: true %>
      </div>
      <div class="mb-4">
        <p>Description</p>
        <%= form.text_area :description, class: "w-full p-2 rounded bg-tertiary", required: true %>
      </div>
      <div class="mb-4">
        <p>Estimated date</p>
        <%= form.date_field :estimated_completion_at, class: "w-full p-2 rounded bg-tertiary", required: true %>
      </div>
      <div class="flex justify-end">
        <%= form.submit "Crear", class: "bg-blue-500 text-white px-4 py-2 rounded bg-tertiary cursor-pointer hover:bg-opacity-50" %>
      </div>
    <% end %>
  </div>
</div>