config/routes.rb
Rails.application.routes.draw do
  # mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
  # get 'confirm_registration', to: 'registrations#confirm'
  resource :registration, only: [:new, :create]
  resources :passwords, param: :token
  resources :objectives, only: [:create, :update, :destroy]


  get 'sign_in', to: 'sessions#new', as: :new_session
  post 'sign_in', to: 'sessions#create', as: :create_session
  delete 'sign_out', to: 'sessions#destroy', as: :destroy_session
  
  get 'account', to: 'users#account', as: :account
  resources :users do
    member do
      patch :update_profile_image
      delete :delete_profile_image
    end
  end
  
  post 'objective/rate', to: 'objectives#rate', as: :rate_objective
  get 'objective/:id', to: 'objectives#details', as: :objective_details

  get 'leader_dashboard', to: 'leaders#dashboard', as: :leader_dashboard
  
  get 'admin_dashboard', to: 'admins#dashboard', as: :admin_dashboard

  get 'users_roles', to: 'users#show_all', as: :users_roles

  patch 'users_roles.:id', to: 'users#set_user_role', as: :set_user_role

  get 'leadership', to: 'leaderships#show', as: :leadership
  post 'leadership', to: 'leaderships#create', as: :leadership_create
  delete 'leadership.:id', to: 'leaderships#destroy', as: :leadership_destroy


  get "up" => "rails/health#show", as: :rails_health_check

  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Trails" %></title>
    <%= favicon_link_tag 'icon.svg' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="bg-primary text-quaternary">
    <main class="flex flex-col mt-[60px] items-center min-h-screen min-w-screen">
      <%= render 'shared/flash' %>
      <% unless current_page?(new_session_path) || current_page?(new_registration_path) %>
        <%= render 'shared/menu' %>
      <% end %>
      <div class="min-w-full max-w-screen-lg">
        <%= yield %>
      </div>
    </main>
  </body>
</html>